### ISSUE TITLE
Ventilators 

### ISSUE THREAD

**Issue by sambuxton** [KyleAvalani/capstone#12]
-Create NPC that, when you talk to them, they drop a ventilator (Lab block)

-Include book in library that tells you which NPC to talk to

-Change doctor's dialog to request ventilators

-Set up code so that when you place a lab block a villager is teleported there after a few minutes

**Comment by nimamoslemy** [comment]
Hi, we are a team that needs your feedback to complete our idea.
Please visit our pages and comment on it. 
[github](https://github.com/nimamoslemy/ventilator)
[gitlab](https://gitlab.com/nimamoslemy/avp-ventilator)

**Comment by sambuxton** [comment]
When you talk to NPC now, villager is teleported to tent and lab block (enchantment table) is teleported to hospital tent.
