### ISSUE TITLE
Factory Owner

### ISSUE THREAD

**Issue by thoalala** [KyleAvalani/capstone#2]
Needs to create a factory owner that players will talk to in order to complete the last action item of Unit 1. 

AC: 

- The NPC is inside the factory
- He wants to go from coal to solar panel but the player must first shut down the pipe that is polluting the lake

**Comment by thoalala** [comment]
- On start command for clone NPC (research)

- Trap door to change dialog

**Comment by sambuxton** [comment]
All done! The trap doors are currently connected to a lever but can be connected to the solar panels.
